---
- name: Install RHEL & Debian packages
  become: yes

  hosts: all
  vars:
   - package_name: netdata
  tasks:
    # Install RHEL family OS service
    - name: Install RHEL Family OS package
      yum:
        name: '{{ package_name }}'
        state: present
      when: ansible_os_family == "RedHat"

    # Install Debian Family OS service

    - name: Install Debian Family package
      apt:
        name: '{{ package_name }}'
        state: present
      when: ansible_os_family == "Debian"