---
- name: Upgrade RHEL & Debian
  become: yes

  hosts: all
  vars:
   - package_name: httpd
  tasks:
    # Install RHEL family OS package
    - name: Install RHEL Family OS package
      yum:
        name: '{{ package_name }}'
        state: present
      when: ansible_os_family == "RedHat"

    # Install Debian Family OS package
    - name: Update repositories cache
      apt:
        update_cache: yes
      when: ansible_os_family == "Debian"
    - name: Install Debian Family package
      apt:
        name: '{{ package_name }}'
        state: present
      when: ansible_os_family == "Debian"
