- hosts: minion
  become: yes

  tasks:

  - name: Instalando nginx
    package:
      name: nginx
      state: present

  - name: Carregamento durante boot nginx
    service:
      name: nginx
      state: restarted
      enabled: yes
      

