- hosts: docker
  become: yes

  tasks:

  - name: Clone do repo
    git:
      repo: 'https://github.com/rmnobarra/rundeck.git'
      dest: /home/sysadmin/rundeck
      update: yes

  - name: Deploy Docker Compose stack
    shell:
      cmd: "docker-compose up -d"
      chdir: /home/sysadmin/rundeck/files/compose
