- hosts: docker
  become: yes

  tasks:

  - name: Clone do repo
    ansible.builtin.git:
      repo: 'https://github.com/rmnobarra/rundeck.git'
      dest: /home/sysadmin/rundeck
      update: yes

  - name: deploy Docker Compose stack
    become_user: root
    docker_compose:
      project_src: /home/sysadmin/rundeck/files/compose
      files:
      - docker-compose.yml
